### ISSUE TITLE
clarifying question about commas

### ISSUE THREAD

**Issue by tpapp** [jrevels/YASGuide#3]
I really like this style guide (as it mostly codifies what I do already :wink:).

Regarding

> Use a single space after commas and semicolons.

even after type parameters? Eg

```julia
struct Foo{T, S}
end
```

I would be happy with the comma, but it is consistently *not* used by many.

**Comment by jrevels** [comment]
I mainly followed JuMP's style guide here, but this is a rule that I, myself, have trouble following! 

My initial reaction was that it does make signatures look a bit spacious. I'm slowly getting used to it, but I think you're right that the space is more commonly elided for type parameters.

Similarly, the `use spaces around binary operators` rule implies spaces around `<:` in type parameter lists:

```julia
struct Foo{T <: Int, S <: String}
end
```

Which seems way too spacious for me! 

I think this reads way better:

```julia
struct Foo{T<:Int, S<:String}
end
```

The only problem is that I think `<:` reads better with the spaces when it's being used outside of type parameter lists...hmm...

**Comment by HarrisonGrodin** [comment]
It seems like the most common practice here, intentional or not, is to use whitespace *only* to separate top-level arguments within an expression. This visually encourages separation between the arguments of a given expression which are most directly relevant to the expression as a whole.

```julia
struct MyType{T<:Number, S<:String}
    a::T
    b::Pair{T,S}
end

f(x::Array{Int,3}, (y,z)::MyType{Int,String}) = (x, y, z)

const MySpecific = MyType{Int, String}

truth = MySpecific <: MyType{<:Integer,String}
```

In the `struct` definition, whitespace is used to separate the two type parameters but not the `<:` operator (which here isn't at the topmost level). However, in the definition of `f`, type parameters (and tuple-destructured variables) have no spacing between, since the primary distinction is between the arguments themselves.

I'm not sure if this should actually be considered good practice (or how to best express "top-level arguments" formally), though.

**Comment by HarrisonGrodin** [comment]
(It might also be worth noting how Julia currently handles these situations, either for inspiration or for potential modification when this issue is resolved.)

```julia
julia> :(struct Foo{T<:Int, S<:String} end)
:(struct Foo{T <: Int, S <: String}
      #= REPL[1]:1 =#
  end)

julia> Array{Int, 3}
Array{Int64,3}
```

**Comment by jrevels** [comment]
I've made an executive decision [here to make type parameter lists special with regards to spacing](https://github.com/jrevels/YASGuide/commit/1ab6daf9092e92034ae3a7515678bf4a9134cca5); basically, the rule now is no spaces in type parameter lists. I think this is an easy exception to remember and maps better to readability/existing usage.
