### ISSUE TITLE
allow two word method name to be connected?

### ISSUE THREAD

**Issue by Roger-luo** [jrevels/YASGuide#9]
This will make it more consistent to `Base`, available name examples e.g

```
ismatch
topangle
meshgrid
```

And maybe methods more than three words should be in snake case then?

**Comment by tk3369** [comment]
I found the official rule (try to smash words together unless it becomes confusing) too relaxed and unsatisfying because the decision is too subjective to the individual programmer and that often leads to inconsistency.  

IMHO, the convention of always separating words with underscores for method names is a good one.

**Comment by jrevels** [comment]
Fully agreed with @tk3369.

Honestly, me wanting to formally move away from Base's weirdness in this regard is one of the reasons I started this guide. Thanks for filing the issue, but I'm going to close it as I really don't wish change this one.
